"""Runtime VM that assembles definition frames and executes them."""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any

import yaml
from drivers.file import create_artifact_directory, remove_artifact, write_text_artifact

from .compiler import Compiler
from .definition import Definition, InputConstraint
from .dispatcher import Dispatcher
from .jinja_engine import JinjaEngine
from .scope_frame import ScopeFrame
from .shell_environment import ShellEnvironment

VERSION = "1.0.0"
GENERATED_DOC_MARKER = "<!-- Generated by workflows.yaml docs/api/reference; do not edit. -->"


def coerce_type(val: Any, expected_type: str) -> Any:
    if val is None:
        return None
    if expected_type == "boolean":
        if isinstance(val, bool):
            return val
        s = str(val).strip().lower()
        if s in ("true", "yes", "1"):
            return True
        if s in ("false", "no", "0", ""):
            return False
        raise ValueError(f"Cannot coerce {val!r} to boolean.")
    if expected_type == "number":
        if isinstance(val, bool):
            raise ValueError(f"Cannot coerce {val!r} to number.")
        if isinstance(val, (int, float)):
            return val
        try:
            s = str(val)
            return int(s) if "." not in s else float(s)
        except (ValueError, TypeError) as exc:
            raise ValueError(f"Cannot coerce {val!r} to number.") from exc
    if expected_type == "array":
        if isinstance(val, list):
            return list(val)
        return [item.strip() for item in str(val).split(",")]
    return str(val)


class Runtime:
    def __init__(
        self,
        env: ShellEnvironment | None = None,
        dispatcher: Dispatcher | None = None,
        jinja_engine: JinjaEngine | None = None,
        system_debug: bool = False,
    ) -> None:
        self.env: ShellEnvironment = env or ShellEnvironment()
        self.registry: dict[str, Definition] = {}
        self.imported_yaml_files: set[str] = set()
        self.definition_sources: dict[str, str] = {}
        self.compiler = Compiler(self.registry)
        self.dispatcher = dispatcher or Dispatcher()
        self.jinja = jinja_engine or JinjaEngine()
        self.globals: dict[str, Any] = {
            "version": VERSION,
            "system_debug": system_debug,
            "registry": list(self.registry.keys()),
            "catalog": {"definitions": [], "tags": []},
        }
        # Expose jinja_env attribute for spec compliance.
        self.jinja_env = self.jinja.env

    # --- YAML import ----------------------------------------------------

    def import_yaml(self, file_path: str) -> list[Definition]:
        normalized_path = os.path.realpath(os.path.abspath(file_path))
        if normalized_path in self.imported_yaml_files:
            return []

        self.imported_yaml_files.add(normalized_path)
        try:
            loaded = self.compiler.import_file(normalized_path)
            for definition in loaded:
                self.definition_sources[definition.id] = normalized_path
            for definition in list(loaded):
                for module in definition.modules:
                    module_path = os.path.join(os.path.dirname(normalized_path), module)
                    loaded.extend(self.import_yaml(module_path))
        except Exception:
            self.imported_yaml_files.discard(normalized_path)
            raise
        self._update_catalog()
        return loaded

    def import_yaml_raw(self, raw: object) -> list[Definition]:
        loaded = self.compiler.import_raw(raw)
        for definition in loaded:
            self.definition_sources[definition.id] = "<raw>"
        self._update_catalog()
        return loaded

    # --- Definition assembly --------------------------------------------

    def assemble_definition_frame(self, def_id: str) -> Definition:
        if def_id not in self.registry:
            raise KeyError(f"Unknown definition id: {def_id!r}")
        self.compiler.detect_cycle(def_id, set(), set())
        return self._assemble(def_id, set())

    def _assemble(self, def_id: str, in_progress: set[str]) -> Definition:
        if def_id in in_progress:
            raise ValueError(f"Cyclic inheritance detected: {def_id} forms a loop.")
        in_progress.add(def_id)

        original = self.registry[def_id]

        # Order: base_parent → mixin1 → mixin2 → ... → local. Child overrides parent.
        variables: dict[str, Any] = {}
        inputs: dict[str, InputConstraint] = {}
        run: list[dict[str, Any]] = []
        teardown: list[dict[str, Any]] = []

        if original.extends:
            parent = self._assemble(original.extends, in_progress)
            variables.update(parent.variables)
            inputs.update(parent.inputs)
            run.extend(parent.run)
            teardown.extend(parent.teardown)

        for mixin_id in original.mixins:
            mixin = self._assemble(mixin_id, in_progress)
            variables.update(mixin.variables)
            inputs.update(mixin.inputs)
            run.extend(mixin.run)
            teardown.extend(mixin.teardown)

        # Local overrides everything.
        variables.update(original.variables)
        inputs.update(original.inputs)
        if original.run:
            run = list(original.run)
        if original.teardown:
            teardown = list(original.teardown)

        in_progress.remove(def_id)
        return Definition(
            id=original.id,
            title=original.title,
            description=original.description,
            tags=list(original.tags),
            extends=original.extends,
            mixins=list(original.mixins),
            modules=list(original.modules),
            run=run,
            variables=variables,
            inputs=inputs,
            teardown=teardown,
            docs=original.docs,
        )

    # --- Documentation catalog -----------------------------------------

    def _update_catalog(self) -> None:
        self.globals["registry"] = list(self.registry.keys())
        entries: dict[str, dict[str, Any]] = {}
        for def_id, definition in self.registry.items():
            entries[def_id] = {
                "id": def_id,
                "title": definition.title or def_id,
                "description": definition.description,
                "tags": list(definition.tags),
                "source_path": self._display_source(self.definition_sources.get(def_id, "<raw>")),
                "page_path": f"definitions/{def_id}.md",
                "mermaid_id": _mermaid_id(def_id),
                "extends": definition.extends,
                "mixins": list(definition.mixins),
                "modules": list(definition.modules),
                "declared": {
                    "inputs": self._input_entries(definition.inputs, def_id),
                    "variables": self._variable_entries(definition, def_id),
                    "run": self._block_entries(definition.run, definition.docs.run, def_id),
                    "teardown": self._block_entries(
                        definition.teardown, definition.docs.teardown, def_id
                    ),
                },
                "children": [],
                "mixin_consumers": [],
            }
        for entry in entries.values():
            def_id = entry["id"]
            parent = entry["extends"]
            if parent in entries:
                entries[parent]["children"].append(def_id)
            for mixin in entry["mixins"]:
                if mixin in entries:
                    entries[mixin]["mixin_consumers"].append(def_id)
        for def_id, entry in entries.items():
            resolved = self._resolved_entries(def_id, set())
            entry["resolved"] = resolved
            entry["index_link"] = os.path.relpath("README.md", os.path.dirname(entry["page_path"]))
            entry["schema_link"] = os.path.relpath("schema.md", os.path.dirname(entry["page_path"]))
            entry["parent"] = self._relation(entries, def_id, entry["extends"])
            entry["mixin_links"] = [
                self._relation(entries, def_id, target) for target in entry["mixins"]
            ]
            entry["child_links"] = [
                self._relation(entries, def_id, target) for target in entry["children"]
            ]
            entry["consumer_links"] = [
                self._relation(entries, def_id, target) for target in entry["mixin_consumers"]
            ]
            for kind in ("inputs", "variables", "run", "teardown"):
                for member in resolved[kind]:
                    relation = self._relation(entries, def_id, member["origin"])
                    member["origin_title"] = relation["title"]
                    member["origin_link"] = relation["link"]
        tag_entries = []
        for tag in sorted({tag for item in entries.values() for tag in item["tags"]}):
            tag_entries.append(
                {
                    "name": tag,
                    "definitions": [item for item in entries.values() if tag in item["tags"]],
                }
            )
        self.globals["catalog"] = {
            "definitions": list(entries.values()),
            "tags": tag_entries,
            "generated_marker": GENERATED_DOC_MARKER,
        }

    def _display_source(self, source: str) -> str:
        if source == "<raw>":
            return source
        return os.path.relpath(source, self.env.cwd)

    def _relation(
        self, entries: dict[str, dict[str, Any]], source_id: str, target_id: str | None
    ) -> dict[str, str] | None:
        if not target_id or target_id not in entries:
            return None
        source_page = entries[source_id]["page_path"]
        target_page = entries[target_id]["page_path"]
        return {
            "id": target_id,
            "title": entries[target_id]["title"],
            "link": os.path.relpath(target_page, os.path.dirname(source_page)),
            "mermaid_id": entries[target_id]["mermaid_id"],
        }

    def _input_entries(
        self, inputs: dict[str, InputConstraint], origin: str
    ) -> list[dict[str, Any]]:
        return [
            {
                "name": name,
                "type": constraint.type,
                "required": constraint.required,
                "default": constraint.default,
                "description": constraint.description,
                "origin": origin,
            }
            for name, constraint in inputs.items()
        ]

    def _variable_entries(self, definition: Definition, origin: str) -> list[dict[str, Any]]:
        return [
            {
                "name": name,
                "value": value,
                "type": type(value).__name__,
                "description": definition.docs.variables.get(name, ""),
                "origin": origin,
            }
            for name, value in definition.variables.items()
        ]

    def _block_entries(
        self, blocks: list[dict[str, Any]], docs: list[Any], origin: str
    ) -> list[dict[str, Any]]:
        entries = []
        for index, block in enumerate(blocks):
            operation = "invoke" if "invoke" in block else next(iter(block), "unknown")
            source = block.get(operation)
            if not isinstance(source, str):
                source = yaml.safe_dump(block, sort_keys=False).rstrip()
            documented = docs[index] if index < len(docs) else None
            entries.append(
                {
                    "operation": operation,
                    "source": source,
                    "title": documented.title if documented else "",
                    "description": documented.description if documented else "",
                    "origin": origin,
                }
            )
        return entries

    def _resolved_entries(
        self, def_id: str, processing: set[str]
    ) -> dict[str, list[dict[str, Any]]]:
        if def_id in processing:
            raise ValueError(f"Cyclic inheritance detected: {def_id} forms a loop.")
        processing.add(def_id)
        definition = self.registry[def_id]
        inputs: dict[str, dict[str, Any]] = {}
        variables: dict[str, dict[str, Any]] = {}
        run: list[dict[str, Any]] = []
        teardown: list[dict[str, Any]] = []
        dependencies = ([definition.extends] if definition.extends else []) + definition.mixins
        for dependency in dependencies:
            resolved = self._resolved_entries(dependency, processing)
            inputs.update({item["name"]: dict(item) for item in resolved["inputs"]})
            variables.update({item["name"]: dict(item) for item in resolved["variables"]})
            run.extend(dict(item) for item in resolved["run"])
            teardown.extend(dict(item) for item in resolved["teardown"])
        inputs.update(
            {item["name"]: item for item in self._input_entries(definition.inputs, def_id)}
        )
        variables.update(
            {item["name"]: item for item in self._variable_entries(definition, def_id)}
        )
        local_run = self._block_entries(definition.run, definition.docs.run, def_id)
        local_teardown = self._block_entries(definition.teardown, definition.docs.teardown, def_id)
        if local_run:
            run = local_run
        if local_teardown:
            teardown = local_teardown
        processing.remove(def_id)
        return {
            "inputs": list(inputs.values()),
            "variables": list(variables.values()),
            "run": run,
            "teardown": teardown,
        }

    # --- Execution ------------------------------------------------------

    def execute(
        self,
        def_id: str,
        arguments: dict[str, Any] | None = None,
        parent_scope: ScopeFrame | None = None,
    ) -> dict[str, Any]:
        arguments = dict(arguments or {})
        assembled = self.assemble_definition_frame(def_id)

        scope = ScopeFrame(parent=parent_scope)
        scope.set("entity_id", def_id)

        # 1. Apply input constraints — coerce types, fill defaults, enforce required.
        coerced_inputs = self._resolve_inputs(assembled.inputs, arguments, scope)
        for k, v in coerced_inputs.items():
            scope.set(k, v)

        # 2. Render variables via multi-pass Jinja; bind into scope as we go so later
        # variables can reference earlier ones.
        for name, raw_val in assembled.variables.items():
            ctx = scope.build_jinja_context(self.globals, self.env)
            scope.set(name, self.jinja.render_value(raw_val, ctx))

        # 3. Execute run blocks; teardown runs in finally regardless of outcome.
        try:
            self._run_blocks(assembled.run, scope)
        finally:
            if assembled.teardown:
                try:
                    self._run_blocks(assembled.teardown, scope)
                except Exception as teardown_exc:  # pragma: no cover - defensive
                    import sys

                    sys.stderr.write(f"Teardown failed: {teardown_exc}\n")

        return dict(scope.local_store)

    def _resolve_inputs(
        self,
        constraints: dict[str, InputConstraint],
        arguments: dict[str, Any],
        scope: ScopeFrame,
    ) -> dict[str, Any]:
        resolved: dict[str, Any] = {}
        # First pass: render defaults that might reference env/runtime.
        for name, constraint in constraints.items():
            if name in arguments and arguments[name] is not None:
                resolved[name] = coerce_type(arguments[name], constraint.type)
            elif constraint.default is not None:
                ctx = scope.build_jinja_context(self.globals, self.env)
                rendered = self.jinja.render_value(constraint.default, ctx)
                resolved[name] = coerce_type(rendered, constraint.type)
            elif constraint.required:
                raise ValueError(f"Missing required input {name!r} (type={constraint.type}).")
        return resolved

    def _run_blocks(self, blocks: list[dict[str, Any]], scope: ScopeFrame) -> None:
        for block in blocks:
            if not isinstance(block, dict):
                raise ValueError("Each run block must be a mapping.")
            if "invoke" in block:
                self._run_invoke(block, scope)
                continue
            if "template" in block:
                if set(block) != {"template"}:
                    raise ValueError("A template block cannot contain additional keys.")
                self._run_template(block["template"], scope)
                continue
            if "generated_pages" in block:
                if set(block) != {"generated_pages"}:
                    raise ValueError("A generated_pages block cannot contain additional keys.")
                self._run_generated_pages(block["generated_pages"], scope)
                continue
            if "artifact" in block:
                if set(block) != {"artifact"}:
                    raise ValueError("An artifact block cannot contain additional keys.")
                self._run_artifact(block["artifact"], scope)
                continue
            if len(block) != 1:
                raise ValueError(
                    "Each script block must be a single-key mapping like {bash: '...'}."
                )
            language, source = next(iter(block.items()))
            if not self.dispatcher.supports(language):
                raise ValueError(f"Unsupported language in run block: {language!r}")
            ctx = scope.build_jinja_context(self.globals, self.env)
            rendered_source = self.jinja.render(source, ctx)
            result = self.dispatcher.dispatch(
                language,
                rendered_source,
                base_env=self.env.env,
                cwd=self.env.cwd,
            )
            if result.state_updates:
                scope.update(result.state_updates)

    def _run_invoke(self, block: dict[str, Any], scope: ScopeFrame) -> None:
        if set(block) - {"invoke", "for_each"}:
            raise ValueError("An invoke block supports only 'invoke' and optional 'for_each'.")
        invoke = block["invoke"]
        if not isinstance(invoke, dict) or "definition" not in invoke:
            raise ValueError("An invoke block requires a definition.")
        context = scope.build_jinja_context(self.globals, self.env)
        items: list[Any] = [None]
        alias = ""
        if "for_each" in block:
            loop = block["for_each"]
            if not isinstance(loop, dict) or "items" not in loop or "as" not in loop:
                raise ValueError("An invoke for_each block requires 'items' and 'as'.")
            evaluated = self.jinja.evaluate(loop["items"], context)
            if not isinstance(evaluated, (list, tuple)):
                raise ValueError("An invoke for_each expression must evaluate to a collection.")
            items = list(evaluated)
            alias = str(loop["as"])
        for item in items:
            invocation_scope = scope
            if alias:
                invocation_scope = ScopeFrame(parent=scope)
                invocation_scope.set(alias, item)
            invocation_context = invocation_scope.build_jinja_context(self.globals, self.env)
            target = self.jinja.render_value(invoke["definition"], invocation_context)
            arguments = self.jinja.render_value(invoke.get("arguments") or {}, invocation_context)
            if target not in self.registry:
                raise KeyError(f"Unknown invoked definition id: {target!r}")
            self.execute(str(target), arguments, parent_scope=invocation_scope)

    def _run_template(self, raw: Any, scope: ScopeFrame) -> None:
        if not isinstance(raw, dict):
            raise ValueError("A template block must be a mapping.")
        context = scope.build_jinja_context(self.globals, self.env)
        config = self.jinja.render_value(raw, context)
        source_path = Path(str(config.get("source_path", "")))
        target_path = Path(str(config.get("target_path", "")))
        mode = str(config.get("mode", "write"))
        if mode not in {"write", "check"}:
            raise ValueError("Template mode must be 'write' or 'check'.")
        template = source_path.read_text(encoding="utf-8")
        rendered = self.jinja.render_template(template, context)
        if mode == "check":
            if not target_path.exists() or target_path.read_text(encoding="utf-8") != rendered:
                raise RuntimeError(f"Generated documentation is stale: {target_path}")
            return
        write_text_artifact(target_path, rendered)

    def _run_generated_pages(self, raw: Any, scope: ScopeFrame) -> None:
        if not isinstance(raw, dict):
            raise ValueError("A generated_pages block must be a mapping.")
        context = scope.build_jinja_context(self.globals, self.env)
        directory = Path(str(self.jinja.render_value(raw.get("directory", ""), context)))
        mode = str(self.jinja.render_value(raw.get("mode", "write"), context))
        expected_expr = raw.get("expected", "runtime.catalog.definitions")
        definitions = self.jinja.evaluate(expected_expr, context)
        expected = {directory / f"{definition['id']}.md" for definition in definitions}
        if not directory.exists():
            return
        for page in directory.rglob("*.md"):
            if page in expected or GENERATED_DOC_MARKER not in page.read_text(encoding="utf-8"):
                continue
            if mode == "check":
                raise RuntimeError(f"Obsolete generated documentation page remains: {page}")
            remove_artifact(page)

    def _run_artifact(self, raw: Any, scope: ScopeFrame) -> None:
        if not isinstance(raw, dict):
            raise ValueError("An artifact block must be a mapping.")
        context = scope.build_jinja_context(self.globals, self.env)
        config = self.jinja.render_value(raw, context)
        action = config.get("action")
        target_path = str(config.get("target_path", ""))
        if action == "write_text":
            content = str(config.get("content", ""))
            if config.get("restore_template_markers"):
                content = content.replace("[[OPEN_TEMPLATE]]", "{" * 2)
                content = content.replace("[[CLOSE_TEMPLATE]]", "}" * 2)
            write_text_artifact(target_path, content)
            return
        if action == "create_directory":
            create_artifact_directory(target_path)
            return
        raise ValueError(f"Unsupported artifact action: {action!r}")


def _mermaid_id(def_id: str) -> str:
    return "def_" + re.sub(r"[^A-Za-z0-9_]", "_", def_id)
