"""Runtime VM that assembles definition frames and executes them."""

from __future__ import annotations

import json
import os
import plistlib
import re
from io import BytesIO
from pathlib import Path
from typing import Any

import yaml
from .file_io import create_artifact_directory, remove_artifact, write_text_artifact

from .compiler import Compiler
from .definition import Definition, InputConstraint, TemplateBlock
from .dispatcher import Dispatcher
from .jinja_engine import JinjaEngine
from .scope_frame import ScopeFrame
from .shell_environment import ShellEnvironment

VERSION = "1.0.0"
GENERATED_DOC_MARKER = "<!-- Generated by docs.api.reference; do not edit. -->"


def coerce_type(val: Any, expected_type: str) -> Any:
    if val is None:
        return None
    if expected_type == "object":
        if isinstance(val, dict):
            return dict(val)
        raise ValueError(f"Cannot coerce {type(val).__name__} to object (expected mapping).")
    if expected_type == "boolean":
        if isinstance(val, bool):
            return val
        s = str(val).strip().lower()
        if s in ("true", "yes", "1"):
            return True
        if s in ("false", "no", "0", ""):
            return False
        raise ValueError(f"Cannot coerce {val!r} to boolean.")
    if expected_type == "number":
        if isinstance(val, bool):
            raise ValueError(f"Cannot coerce {val!r} to number.")
        if isinstance(val, (int, float)):
            return val
        try:
            s = str(val)
            return int(s) if "." not in s else float(s)
        except (ValueError, TypeError) as exc:
            raise ValueError(f"Cannot coerce {val!r} to number.") from exc
    if expected_type == "array":
        if isinstance(val, list):
            return list(val)
        return [item.strip() for item in str(val).split(",")]
    return str(val)


class Runtime:
    def __init__(
        self,
        env: ShellEnvironment | None = None,
        dispatcher: Dispatcher | None = None,
        jinja_engine: JinjaEngine | None = None,
        system_debug: bool = False,
        workflow_dir: str | Path | None = None,
        definition_page_format: str = "definitions/definition-{flat_id}.md",
        index_page: str = "README.md",
        schema_page: str = "schema.md",
    ) -> None:
        self.env: ShellEnvironment = env or ShellEnvironment()
        self.registry: dict[str, Definition] = {}
        self.imported_yaml_files: set[str] = set()
        self.definition_sources: dict[str, str] = {}
        self.compiler = Compiler(self.registry)
        self.dispatcher = dispatcher or Dispatcher()
        self.jinja = jinja_engine or JinjaEngine()
        self._definition_page_format = definition_page_format
        self._index_page = index_page
        self._schema_page = schema_page
        self.globals: dict[str, Any] = {
            "version": VERSION,
            "system_debug": system_debug,
            "registry": list(self.registry.keys()),
            "catalog": {"definitions": [], "tags": []},
            "workflow_dir": str(Path(workflow_dir).resolve()) if workflow_dir else "",
        }
        # Expose jinja_env attribute for spec compliance.
        self.jinja_env = self.jinja.env

    # --- YAML import ----------------------------------------------------

    def import_yaml(self, file_path: str) -> list[Definition]:
        normalized_path = os.path.realpath(os.path.abspath(file_path))
        if normalized_path in self.imported_yaml_files:
            return []

        self.imported_yaml_files.add(normalized_path)
        try:
            loaded = self.compiler.import_file(normalized_path)
            for definition in loaded:
                self.definition_sources[definition.id] = normalized_path
            for definition in list(loaded):
                for module in definition.modules:
                    module_path = os.path.join(os.path.dirname(normalized_path), module)
                    loaded.extend(self.import_yaml(module_path))
        except Exception:
            self.imported_yaml_files.discard(normalized_path)
            raise
        self._update_catalog()
        return loaded

    def import_yaml_raw(self, raw: object) -> list[Definition]:
        loaded = self.compiler.import_raw(raw)
        for definition in loaded:
            self.definition_sources[definition.id] = "<raw>"
        self._update_catalog()
        return loaded

    # --- Definition assembly --------------------------------------------

    def assemble_definition_frame(self, def_id: str) -> Definition:
        if def_id not in self.registry:
            raise KeyError(f"Unknown definition id: {def_id!r}")
        self.compiler.detect_cycle(def_id, set(), set())
        return self._assemble(def_id, set())

    def _assemble(self, def_id: str, in_progress: set[str]) -> Definition:
        if def_id in in_progress:
            raise ValueError(f"Cyclic inheritance detected: {def_id} forms a loop.")
        in_progress.add(def_id)

        original = self.registry[def_id]

        # Order: base_parent → mixin1 → mixin2 → ... → local. Child overrides parent.
        variables: dict[str, Any] = {}
        inputs: dict[str, InputConstraint] = {}
        run: list[dict[str, Any]] = []
        teardown: list[dict[str, Any]] = []
        schema: dict[str, Any] = {}
        launchd: dict[str, Any] = {}

        if original.extends:
            parent = self._assemble(original.extends, in_progress)
            variables.update(parent.variables)
            inputs.update(parent.inputs)
            run.extend(parent.run)
            teardown.extend(parent.teardown)
            schema = _deep_merge_schema(schema, parent.schema)
            launchd = _deep_merge_schema(launchd, parent.launchd)

        for mixin_id in original.mixins:
            mixin = self._assemble(mixin_id, in_progress)
            variables.update(mixin.variables)
            inputs.update(mixin.inputs)
            run.extend(mixin.run)
            teardown.extend(mixin.teardown)
            schema = _deep_merge_schema(schema, mixin.schema)
            launchd = _deep_merge_schema(launchd, mixin.launchd)

        # Local overrides everything.
        variables.update(original.variables)
        inputs.update(original.inputs)
        if original.run:
            run = list(original.run)
        if original.teardown:
            teardown = list(original.teardown)
        schema = _deep_merge_schema(schema, original.schema)
        launchd = _deep_merge_schema(launchd, original.launchd)

        in_progress.remove(def_id)
        return Definition(
            id=original.id,
            title=original.title,
            description=original.description,
            tags=list(original.tags),
            extends=original.extends,
            mixins=list(original.mixins),
            modules=list(original.modules),
            run=run,
            variables=variables,
            inputs=inputs,
            teardown=teardown,
            docs=original.docs,
            template=original.template,
            schema=schema,
            launchd=launchd,
        )

    # --- Documentation catalog -----------------------------------------

    def _update_catalog(self) -> None:
        self.globals["registry"] = list(self.registry.keys())
        entries: dict[str, dict[str, Any]] = {}
        for def_id, definition in self.registry.items():
            entries[def_id] = {
                "id": def_id,
                "title": definition.title or def_id,
                "description": definition.description,
                "tags": list(definition.tags),
                "source_path": self._display_source(self.definition_sources.get(def_id, "<raw>")),
                "page_path": self._definition_page_format.format(
                    flat_id=_flat_def_id(def_id), id=def_id
                ),
                "mermaid_id": _mermaid_id(def_id),
                "extends": definition.extends,
                "mixins": list(definition.mixins),
                "modules": list(definition.modules),
                "schema": dict(definition.schema),
                "has_schema": bool(definition.schema),
                "launchd": dict(definition.launchd),
                "has_launchd": bool(definition.launchd),
                "has_command": self._descends_from(def_id, "command.base"),
                "has_docker": self._descends_from(def_id, "docker.base"),
                "has_model": self._descends_from(def_id, "model.base"),
                "has_provider": self._descends_from(def_id, "provider.base"),
                "has_folder": self._descends_from(def_id, "folder.base"),
                "has_route": self._descends_from(def_id, "route.base"),
                "has_service": self._descends_from(def_id, "service.base"),
                "declared": {
                    "inputs": self._input_entries(definition.inputs, def_id),
                    "variables": self._variable_entries(definition, def_id),
                    "run": self._block_entries(definition.run, definition.docs.run, def_id),
                    "teardown": self._block_entries(
                        definition.teardown, definition.docs.teardown, def_id
                    ),
                },
                "children": [],
                "mixin_consumers": [],
            }
        for entry in entries.values():
            def_id = entry["id"]
            parent = entry["extends"]
            if parent in entries:
                entries[parent]["children"].append(def_id)
            for mixin in entry["mixins"]:
                if mixin in entries:
                    entries[mixin]["mixin_consumers"].append(def_id)
        for def_id, entry in entries.items():
            resolved = self._resolved_entries(def_id, set())
            entry["resolved"] = resolved
            entry["index_link"] = os.path.relpath(
                self._index_page, os.path.dirname(entry["page_path"]) or "."
            )
            entry["schema_link"] = os.path.relpath(
                self._schema_page, os.path.dirname(entry["page_path"]) or "."
            )
            entry["parent"] = self._relation(entries, def_id, entry["extends"])
            entry["mixin_links"] = [
                self._relation(entries, def_id, target) for target in entry["mixins"]
            ]
            entry["child_links"] = [
                self._relation(entries, def_id, target) for target in entry["children"]
            ]
            entry["consumer_links"] = [
                self._relation(entries, def_id, target) for target in entry["mixin_consumers"]
            ]
            for kind in ("inputs", "variables", "run", "teardown"):
                for member in resolved[kind]:
                    relation = self._relation(entries, def_id, member["origin"])
                    member["origin_title"] = relation["title"]
                    member["origin_link"] = relation["link"]
        tag_entries = []
        for tag in sorted({tag for item in entries.values() for tag in item["tags"]}):
            tag_entries.append(
                {
                    "name": tag,
                    "definitions": [item for item in entries.values() if tag in item["tags"]],
                }
            )
        self.globals["catalog"] = {
            "definitions": list(entries.values()),
            "tags": tag_entries,
            "generated_marker": GENERATED_DOC_MARKER,
        }

    def _display_source(self, source: str) -> str:
        if source == "<raw>":
            return source
        return os.path.relpath(source, self.env.cwd)

    def _descends_from(self, def_id: str, ancestor_id: str) -> bool:
        if def_id == ancestor_id:
            return False
        seen: set[str] = set()
        current = self.registry.get(def_id)
        while current is not None and current.id not in seen:
            seen.add(current.id)
            if current.extends == ancestor_id:
                return True
            if any(self._descends_from(m, ancestor_id) or m == ancestor_id for m in current.mixins):
                return True
            current = self.registry.get(current.extends) if current.extends else None
        return False

    def _relation(
        self, entries: dict[str, dict[str, Any]], source_id: str, target_id: str | None
    ) -> dict[str, str] | None:
        if not target_id or target_id not in entries:
            return None
        source_page = entries[source_id]["page_path"]
        target_page = entries[target_id]["page_path"]
        return {
            "id": target_id,
            "title": entries[target_id]["title"],
            "link": os.path.relpath(target_page, os.path.dirname(source_page)),
            "mermaid_id": entries[target_id]["mermaid_id"],
        }

    def _input_entries(
        self, inputs: dict[str, InputConstraint], origin: str
    ) -> list[dict[str, Any]]:
        return [
            {
                "name": name,
                "type": constraint.type,
                "required": constraint.required,
                "default": constraint.default,
                "description": constraint.description,
                "origin": origin,
            }
            for name, constraint in inputs.items()
        ]

    def _variable_entries(self, definition: Definition, origin: str) -> list[dict[str, Any]]:
        return [
            {
                "name": name,
                "value": value,
                "type": type(value).__name__,
                "description": definition.docs.variables.get(name, ""),
                "origin": origin,
            }
            for name, value in definition.variables.items()
        ]

    def _block_entries(
        self, blocks: list[dict[str, Any]], docs: list[Any], origin: str
    ) -> list[dict[str, Any]]:
        entries = []
        for index, block in enumerate(blocks):
            operation = "invoke" if "invoke" in block else next(iter(block), "unknown")
            source = block.get(operation)
            if not isinstance(source, str):
                source = yaml.safe_dump(block, sort_keys=False).rstrip()
            documented = docs[index] if index < len(docs) else None
            entries.append(
                {
                    "operation": operation,
                    "source": source,
                    "title": documented.title if documented else "",
                    "description": documented.description if documented else "",
                    "origin": origin,
                }
            )
        return entries

    def _resolved_entries(
        self, def_id: str, processing: set[str]
    ) -> dict[str, list[dict[str, Any]]]:
        if def_id in processing:
            raise ValueError(f"Cyclic inheritance detected: {def_id} forms a loop.")
        processing.add(def_id)
        definition = self.registry[def_id]
        inputs: dict[str, dict[str, Any]] = {}
        variables: dict[str, dict[str, Any]] = {}
        run: list[dict[str, Any]] = []
        teardown: list[dict[str, Any]] = []
        dependencies = ([definition.extends] if definition.extends else []) + definition.mixins
        for dependency in dependencies:
            resolved = self._resolved_entries(dependency, processing)
            inputs.update({item["name"]: dict(item) for item in resolved["inputs"]})
            variables.update({item["name"]: dict(item) for item in resolved["variables"]})
            run.extend(dict(item) for item in resolved["run"])
            teardown.extend(dict(item) for item in resolved["teardown"])
        inputs.update(
            {item["name"]: item for item in self._input_entries(definition.inputs, def_id)}
        )
        variables.update(
            {item["name"]: item for item in self._variable_entries(definition, def_id)}
        )
        local_run = self._block_entries(definition.run, definition.docs.run, def_id)
        local_teardown = self._block_entries(definition.teardown, definition.docs.teardown, def_id)
        if local_run:
            run = local_run
        if local_teardown:
            teardown = local_teardown
        processing.remove(def_id)
        return {
            "inputs": list(inputs.values()),
            "variables": list(variables.values()),
            "run": run,
            "teardown": teardown,
        }

    # --- Execution ------------------------------------------------------

    def execute(
        self,
        def_id: str,
        arguments: dict[str, Any] | None = None,
        parent_scope: ScopeFrame | None = None,
    ) -> dict[str, Any]:
        scope, _rendered = self._execute(def_id, arguments, parent_scope)
        return dict(scope.local_store)

    def render_definition(
        self, def_id: str, arguments: dict[str, Any] | None = None
    ) -> str:
        """Execute a template definition and return its rendered body."""
        assembled = self.assemble_definition_frame(def_id)
        if assembled.template is None:
            raise ValueError(
                f"Definition {def_id!r} does not declare a 'template' block."
            )
        _, rendered = self._execute(def_id, arguments, parent_scope=None)
        if rendered is None:  # pragma: no cover - guarded by template check above
            raise RuntimeError(f"Template definition {def_id!r} produced no output.")
        return rendered

    def assemble_schema(self, def_id: str) -> dict[str, Any]:
        """Return the merged JSON Schema document for a schema definition.

        The result combines the `schema:` blocks from `extends`, `mixins`, and
        the local definition (child wins on conflicts; mappings are deep-merged).
        """
        assembled = self.assemble_definition_frame(def_id)
        if not assembled.schema:
            raise ValueError(
                f"Definition {def_id!r} does not declare a 'schema' block."
            )
        return dict(assembled.schema)

    def render_schema_json(self, def_id: str, indent: int = 2) -> str:
        """Return the merged schema serialized as JSON text."""
        schema = self.assemble_schema(def_id)
        return json.dumps(schema, indent=indent, sort_keys=False) + "\n"

    def assemble_launchd(
        self, def_id: str, arguments: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        """Return the merged launchd job spec with friendly snake_case keys.

        Inherited `launchd:` blocks are deep-merged, then every string value is
        passed through Jinja so per-job specs can reference variables (such as
        `{{ user }}`) declared on `launchd.base` or the individual definition.
        """
        assembled = self.assemble_definition_frame(def_id)
        if not assembled.launchd:
            raise ValueError(
                f"Definition {def_id!r} does not declare a 'launchd' block."
            )
        scope = ScopeFrame()
        scope.set("entity_id", def_id)
        coerced_inputs = self._resolve_inputs(assembled.inputs, dict(arguments or {}), scope)
        for k, v in coerced_inputs.items():
            scope.set(k, v)
        for name, raw_val in assembled.variables.items():
            ctx = self._build_template_context(scope)
            scope.set(name, self.jinja.render_value(raw_val, ctx))
        ctx = self._build_template_context(scope)
        return self.jinja.render_value(dict(assembled.launchd), ctx)

    def render_launchd_plist(
        self, def_id: str, arguments: dict[str, Any] | None = None
    ) -> bytes:
        """Return the launchd plist bytes (XML) for a launchd definition."""
        spec = self.assemble_launchd(def_id, arguments)
        plist_dict = _launchd_to_plist(spec)
        buf = BytesIO()
        plistlib.dump(plist_dict, buf, sort_keys=False)
        return buf.getvalue()

    def _execute(
        self,
        def_id: str,
        arguments: dict[str, Any] | None,
        parent_scope: ScopeFrame | None,
    ) -> tuple[ScopeFrame, str | None]:
        arguments = dict(arguments or {})
        assembled = self.assemble_definition_frame(def_id)

        scope = ScopeFrame(parent=parent_scope)
        scope.set("entity_id", def_id)

        # 1. Apply input constraints — coerce types, fill defaults, enforce required.
        coerced_inputs = self._resolve_inputs(assembled.inputs, arguments, scope)
        for k, v in coerced_inputs.items():
            scope.set(k, v)

        # 2. Render variables via multi-pass Jinja; bind into scope as we go so later
        # variables can reference earlier ones.
        for name, raw_val in assembled.variables.items():
            ctx = self._build_template_context(scope)
            scope.set(name, self.jinja.render_value(raw_val, ctx))

        # 3. Execute run blocks; teardown runs in finally regardless of outcome.
        try:
            self._run_blocks(assembled.run, scope)
        finally:
            if assembled.teardown:
                try:
                    self._run_blocks(assembled.teardown, scope)
                except Exception as teardown_exc:  # pragma: no cover - defensive
                    import sys

                    sys.stderr.write(f"Teardown failed: {teardown_exc}\n")

        rendered: str | None = None
        if assembled.template is not None:
            rendered = self._render_template_block(assembled.template, scope)
        return scope, rendered

    def _build_template_context(self, scope: ScopeFrame) -> dict[str, Any]:
        """Jinja context augmented with the `component()` composition helper."""
        ctx = scope.build_jinja_context(self.globals, self.env)
        ctx["component"] = self._component_helper
        return ctx

    def _component_helper(self, definition_id: str, **arguments: Any) -> str:
        return self.render_definition(definition_id, arguments)

    def _render_template_block(
        self, template: TemplateBlock, scope: ScopeFrame
    ) -> str:
        ctx = self._build_template_context(scope)
        if template.engine == "jinja":
            return self.jinja.render_template(template.body, ctx)
        raise ValueError(f"Unsupported template engine: {template.engine!r}")

    def _resolve_inputs(
        self,
        constraints: dict[str, InputConstraint],
        arguments: dict[str, Any],
        scope: ScopeFrame,
    ) -> dict[str, Any]:
        resolved: dict[str, Any] = {}
        # First pass: render defaults that might reference env/runtime.
        for name, constraint in constraints.items():
            if name in arguments and arguments[name] is not None:
                resolved[name] = coerce_type(arguments[name], constraint.type)
            elif constraint.default is not None:
                ctx = self._build_template_context(scope)
                rendered = self.jinja.render_value(constraint.default, ctx)
                resolved[name] = coerce_type(rendered, constraint.type)
            elif constraint.required:
                raise ValueError(f"Missing required input {name!r} (type={constraint.type}).")
        return resolved

    def _run_blocks(self, blocks: list[dict[str, Any]], scope: ScopeFrame) -> None:
        for block in blocks:
            if not isinstance(block, dict):
                raise ValueError("Each run block must be a mapping.")
            if "invoke" in block:
                self._run_invoke(block, scope)
                continue
            if "render" in block:
                self._run_render(block, scope)
                continue
            if "template" in block:
                if set(block) != {"template"}:
                    raise ValueError("A template block cannot contain additional keys.")
                self._run_template(block["template"], scope)
                continue
            if "generated_pages" in block:
                if set(block) != {"generated_pages"}:
                    raise ValueError("A generated_pages block cannot contain additional keys.")
                self._run_generated_pages(block["generated_pages"], scope)
                continue
            if "artifact" in block:
                if set(block) != {"artifact"}:
                    raise ValueError("An artifact block cannot contain additional keys.")
                self._run_artifact(block["artifact"], scope)
                continue
            if "schema_json" in block:
                if set(block) - {"schema_json", "for_each"}:
                    raise ValueError(
                        "A schema_json block supports only 'schema_json' and optional 'for_each'."
                    )
                self._run_schema_json(block, scope)
                continue
            if "launchd_plist" in block:
                if set(block) - {"launchd_plist", "for_each"}:
                    raise ValueError(
                        "A launchd_plist block supports only 'launchd_plist' and optional 'for_each'."
                    )
                self._run_launchd_plist(block, scope)
                continue
            if len(block) != 1:
                raise ValueError(
                    "Each script block must be a single-key mapping like {bash: '...'}."
                )
            language, source = next(iter(block.items()))
            if not self.dispatcher.supports(language):
                raise ValueError(f"Unsupported language in run block: {language!r}")
            ctx = self._build_template_context(scope)
            rendered_source = self.jinja.render(source, ctx)
            result = self.dispatcher.dispatch(
                language,
                rendered_source,
                base_env=self.env.env,
                cwd=self.env.cwd,
            )
            if result.state_updates:
                scope.update(result.state_updates)

    def _run_invoke(self, block: dict[str, Any], scope: ScopeFrame) -> None:
        if set(block) - {"invoke", "for_each"}:
            raise ValueError("An invoke block supports only 'invoke' and optional 'for_each'.")
        invoke = block["invoke"]
        if not isinstance(invoke, dict) or "definition" not in invoke:
            raise ValueError("An invoke block requires a definition.")
        context = self._build_template_context(scope)
        items: list[Any] = [None]
        alias = ""
        if "for_each" in block:
            loop = block["for_each"]
            if not isinstance(loop, dict) or "items" not in loop or "as" not in loop:
                raise ValueError("An invoke for_each block requires 'items' and 'as'.")
            evaluated = self.jinja.evaluate(loop["items"], context)
            if not isinstance(evaluated, (list, tuple)):
                raise ValueError("An invoke for_each expression must evaluate to a collection.")
            items = list(evaluated)
            alias = str(loop["as"])
        for item in items:
            invocation_scope = scope
            if alias:
                invocation_scope = ScopeFrame(parent=scope)
                invocation_scope.set(alias, item)
            invocation_context = self._build_template_context(invocation_scope)
            target = self.jinja.render_value(invoke["definition"], invocation_context)
            arguments = self.jinja.resolve_argument(invoke.get("arguments") or {}, invocation_context)
            if target not in self.registry:
                raise KeyError(f"Unknown invoked definition id: {target!r}")
            self.execute(str(target), arguments, parent_scope=invocation_scope)

    def _run_render(self, block: dict[str, Any], scope: ScopeFrame) -> None:
        if set(block) - {"render", "for_each"}:
            raise ValueError("A render block supports only 'render' and optional 'for_each'.")
        render = block["render"]
        if not isinstance(render, dict) or "definition" not in render:
            raise ValueError("A render block requires a 'definition' field.")
        if "target_path" not in render:
            raise ValueError("A render block requires a 'target_path' field.")
        context = self._build_template_context(scope)
        items: list[Any] = [None]
        alias = ""
        if "for_each" in block:
            loop = block["for_each"]
            if not isinstance(loop, dict) or "items" not in loop or "as" not in loop:
                raise ValueError("A render for_each block requires 'items' and 'as'.")
            evaluated = self.jinja.evaluate(loop["items"], context)
            if not isinstance(evaluated, (list, tuple)):
                raise ValueError("A render for_each expression must evaluate to a collection.")
            items = list(evaluated)
            alias = str(loop["as"])
        for item in items:
            invocation_scope = scope
            if alias:
                invocation_scope = ScopeFrame(parent=scope)
                invocation_scope.set(alias, item)
            invocation_context = self._build_template_context(invocation_scope)
            target_id = str(self.jinja.render_value(render["definition"], invocation_context))
            arguments = self.jinja.resolve_argument(
                render.get("arguments") or {}, invocation_context
            )
            target_path = str(
                self.jinja.render_value(render["target_path"], invocation_context)
            )
            mode = str(self.jinja.render_value(render.get("mode", "write"), invocation_context))
            if mode not in {"write", "check"}:
                raise ValueError("Render mode must be 'write' or 'check'.")
            if target_id not in self.registry:
                raise KeyError(f"Unknown render definition id: {target_id!r}")
            rendered = self.render_definition(target_id, arguments)
            destination = Path(target_path)
            if mode == "check":
                if (
                    not destination.exists()
                    or destination.read_text(encoding="utf-8") != rendered
                ):
                    raise RuntimeError(
                        f"Generated documentation is stale: {destination}"
                    )
                continue
            write_text_artifact(destination, rendered)

    def _run_schema_json(self, block: dict[str, Any], scope: ScopeFrame) -> None:
        config = block["schema_json"]
        if not isinstance(config, dict) or "definition" not in config:
            raise ValueError("A schema_json block requires a 'definition' field.")
        if "target_path" not in config:
            raise ValueError("A schema_json block requires a 'target_path' field.")
        context = self._build_template_context(scope)
        items: list[Any] = [None]
        alias = ""
        if "for_each" in block:
            loop = block["for_each"]
            if not isinstance(loop, dict) or "items" not in loop or "as" not in loop:
                raise ValueError("A schema_json for_each block requires 'items' and 'as'.")
            evaluated = self.jinja.evaluate(loop["items"], context)
            if not isinstance(evaluated, (list, tuple)):
                raise ValueError(
                    "A schema_json for_each expression must evaluate to a collection."
                )
            items = list(evaluated)
            alias = str(loop["as"])
        for item in items:
            invocation_scope = scope
            if alias:
                invocation_scope = ScopeFrame(parent=scope)
                invocation_scope.set(alias, item)
            invocation_context = self._build_template_context(invocation_scope)
            target_id = str(
                self.jinja.render_value(config["definition"], invocation_context)
            )
            target_path = str(
                self.jinja.render_value(config["target_path"], invocation_context)
            )
            mode = str(self.jinja.render_value(config.get("mode", "write"), invocation_context))
            if mode not in {"write", "check"}:
                raise ValueError("schema_json mode must be 'write' or 'check'.")
            indent_raw = self.jinja.render_value(config.get("indent", 2), invocation_context)
            try:
                indent = int(indent_raw)
            except (TypeError, ValueError) as exc:
                raise ValueError(
                    f"schema_json 'indent' must be an integer, got {indent_raw!r}."
                ) from exc
            if target_id not in self.registry:
                raise KeyError(f"Unknown schema definition id: {target_id!r}")
            rendered = self.render_schema_json(target_id, indent=indent)
            destination = Path(target_path)
            if mode == "check":
                if (
                    not destination.exists()
                    or destination.read_text(encoding="utf-8") != rendered
                ):
                    raise RuntimeError(
                        f"Generated schema JSON is stale: {destination}"
                    )
                continue
            write_text_artifact(destination, rendered)

    def _run_launchd_plist(self, block: dict[str, Any], scope: ScopeFrame) -> None:
        config = block["launchd_plist"]
        if not isinstance(config, dict) or "definition" not in config:
            raise ValueError("A launchd_plist block requires a 'definition' field.")
        if "target_path" not in config:
            raise ValueError("A launchd_plist block requires a 'target_path' field.")
        context = self._build_template_context(scope)
        items: list[Any] = [None]
        alias = ""
        if "for_each" in block:
            loop = block["for_each"]
            if not isinstance(loop, dict) or "items" not in loop or "as" not in loop:
                raise ValueError("A launchd_plist for_each block requires 'items' and 'as'.")
            evaluated = self.jinja.evaluate(loop["items"], context)
            if not isinstance(evaluated, (list, tuple)):
                raise ValueError(
                    "A launchd_plist for_each expression must evaluate to a collection."
                )
            items = list(evaluated)
            alias = str(loop["as"])
        for item in items:
            invocation_scope = scope
            if alias:
                invocation_scope = ScopeFrame(parent=scope)
                invocation_scope.set(alias, item)
            invocation_context = self._build_template_context(invocation_scope)
            target_id = str(
                self.jinja.render_value(config["definition"], invocation_context)
            )
            target_path = str(
                self.jinja.render_value(config["target_path"], invocation_context)
            )
            mode = str(self.jinja.render_value(config.get("mode", "write"), invocation_context))
            if mode not in {"write", "check"}:
                raise ValueError("launchd_plist mode must be 'write' or 'check'.")
            if target_id not in self.registry:
                raise KeyError(f"Unknown launchd definition id: {target_id!r}")
            rendered = self.render_launchd_plist(target_id)
            destination = Path(target_path)
            if mode == "check":
                if not destination.exists() or destination.read_bytes() != rendered:
                    raise RuntimeError(
                        f"Generated launchd plist is stale: {destination}"
                    )
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(rendered)

    def _run_template(self, raw: Any, scope: ScopeFrame) -> None:
        if not isinstance(raw, dict):
            raise ValueError("A template block must be a mapping.")
        context = self._build_template_context(scope)
        config = self.jinja.render_value(raw, context)
        source_path = Path(str(config.get("source_path", "")))
        target_path = Path(str(config.get("target_path", "")))
        mode = str(config.get("mode", "write"))
        if mode not in {"write", "check"}:
            raise ValueError("Template mode must be 'write' or 'check'.")
        template = source_path.read_text(encoding="utf-8")
        rendered = self.jinja.render_template(template, context)
        if mode == "check":
            if not target_path.exists() or target_path.read_text(encoding="utf-8") != rendered:
                raise RuntimeError(f"Generated documentation is stale: {target_path}")
            return
        write_text_artifact(target_path, rendered)

    def _run_generated_pages(self, raw: Any, scope: ScopeFrame) -> None:
        if not isinstance(raw, dict):
            raise ValueError("A generated_pages block must be a mapping.")
        context = self._build_template_context(scope)
        directory = Path(str(self.jinja.render_value(raw.get("directory", ""), context)))
        mode = str(self.jinja.render_value(raw.get("mode", "write"), context))
        pattern = str(self.jinja.render_value(raw.get("pattern", "*.md"), context))
        expected_expr = raw.get("expected", "runtime.catalog.definitions")
        definitions = self.jinja.evaluate(expected_expr, context)
        expected = {
            directory / Path(definition["page_path"]).name for definition in definitions
        }
        if not directory.exists():
            return
        for page in directory.rglob(pattern):
            if page in expected or GENERATED_DOC_MARKER not in page.read_text(encoding="utf-8"):
                continue
            if mode == "check":
                raise RuntimeError(f"Obsolete generated documentation page remains: {page}")
            remove_artifact(page)
        if mode == "write":
            # Strip empty subdirectories left behind by retired nested layouts.
            for subdir in sorted(
                (p for p in directory.rglob("*") if p.is_dir()),
                key=lambda p: len(p.parts),
                reverse=True,
            ):
                try:
                    subdir.rmdir()
                except OSError:
                    pass

    def _run_artifact(self, raw: Any, scope: ScopeFrame) -> None:
        if not isinstance(raw, dict):
            raise ValueError("An artifact block must be a mapping.")
        context = self._build_template_context(scope)
        config = self.jinja.render_value(raw, context)
        action = config.get("action")
        target_path = str(config.get("target_path", ""))
        if action == "write_text":
            content = str(config.get("content", ""))
            if config.get("restore_template_markers"):
                content = content.replace("[[OPEN_TEMPLATE]]", "{" * 2)
                content = content.replace("[[CLOSE_TEMPLATE]]", "}" * 2)
            write_text_artifact(target_path, content)
            return
        if action == "create_directory":
            create_artifact_directory(target_path)
            return
        raise ValueError(f"Unsupported artifact action: {action!r}")


def _deep_merge_schema(base: dict[str, Any], overlay: dict[str, Any]) -> dict[str, Any]:
    """Deep-merge schema dicts. Child mappings overlay parent mappings recursively;
    non-mapping values (including lists) at any key are replaced wholesale by the child.
    """
    if not overlay:
        return dict(base)
    if not base:
        return dict(overlay)
    merged = dict(base)
    for key, overlay_value in overlay.items():
        base_value = merged.get(key)
        if isinstance(base_value, dict) and isinstance(overlay_value, dict):
            merged[key] = _deep_merge_schema(base_value, overlay_value)
        else:
            merged[key] = overlay_value
    return merged


_LAUNCHD_KEY_MAP = {
    "label": "Label",
    "program": "ProgramArguments",
    "program_arguments": "ProgramArguments",
    "environment": "EnvironmentVariables",
    "environment_variables": "EnvironmentVariables",
    "working_directory": "WorkingDirectory",
    "process_type": "ProcessType",
    "run_at_load": "RunAtLoad",
    "keep_alive": "KeepAlive",
    "stdout": "StandardOutPath",
    "stderr": "StandardErrorPath",
    "standard_out_path": "StandardOutPath",
    "standard_error_path": "StandardErrorPath",
    "user_name": "UserName",
    "group_name": "GroupName",
    "start_interval": "StartInterval",
    "start_calendar_interval": "StartCalendarInterval",
    "throttle_interval": "ThrottleInterval",
    "soft_resource_limits": "SoftResourceLimits",
    "hard_resource_limits": "HardResourceLimits",
    "nice": "Nice",
    "umask": "Umask",
}

_LAUNCHD_KEEP_ALIVE_KEY_MAP = {
    "successful_exit": "SuccessfulExit",
    "crashed": "Crashed",
    "network_state": "NetworkState",
    "path_state": "PathState",
    "other_job_enabled": "OtherJobEnabled",
}


_LAUNCHD_METADATA_KEYS = frozenset({"name", "category", "description"})


def _launchd_to_plist(spec: dict[str, Any]) -> dict[str, Any]:
    """Translate a friendly snake_case launchd spec into plist-key form.

    Unknown keys are passed through unchanged so authors can supply additional
    launchd keys (PascalCase already) without the runtime needing to know them.
    Pure metadata keys (`name`, `category`, `description`) are skipped — they
    document the entry but don't belong in the plist.
    """
    out: dict[str, Any] = {}
    for key, value in spec.items():
        if key in _LAUNCHD_METADATA_KEYS:
            continue
        plist_key = _LAUNCHD_KEY_MAP.get(key, key)
        if plist_key == "KeepAlive" and isinstance(value, dict):
            value = {
                _LAUNCHD_KEEP_ALIVE_KEY_MAP.get(k, k): v for k, v in value.items()
            }
        out[plist_key] = value
    return out


def _mermaid_id(def_id: str) -> str:
    return "def_" + re.sub(r"[^A-Za-z0-9_]", "_", def_id)


def _flat_def_id(def_id: str) -> str:
    """Flatten a slash-separated definition id to a sibling-friendly filename stem."""
    return def_id.replace("/", "-")
