# Required env: DATA_PATH
# Optional env: PROMETHEUS_PORT (default 9090)
services:
  prometheus:
    image: prom/prometheus
    container_name: contentgraph-prometheus
    restart: unless-stopped
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    ports:
    - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - ${DATA_PATH}:/prometheus
